#!/bin/sh

for x in /tmp/client*
do
  tail $x | grep Average | cut -d' ' -f2
done | awk '
BEGIN { sum=0.0; count=0; }
      { sum += $1; count += 1; printf("%f\n", $1); }
END   { average = sum / count
        printf("%f / %d = %f\n", sum, count, average );
        printf("%f frames per second\n", 1.0 / average); }
'
