APPNAME = fermi

${APPNAME}: fermi_main.m fermi.m
	mcc -m -R -nojvm -I /apps/rappture/lib/matlab -o $@ $^

all: ${APPNAME}

install: ${APPNAME}
	sed s/YOURAPPNAME/$^/ < run_app.patch | patch run_$^.sh
	chmod +x run_$^.sh
	mv $^ $^.ctf run_$^.sh ../bin
	mv readme.txt ../bin/$^.readme
	simsim --tool tool.xml --values default --nosim --driver driver.$^
	LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/apps/rappture/lib `pwd`/../bin/run_$^.sh /apps/matlab/mcr `pwd`/driver.$^
	rm -f run*.xml driver.$^
	@echo "Install Successful"

clean:
	rm -rf ${APPNAME} \
		${APPNAME}_main.c \
		${APPNAME}.ctf \
		${APPNAME}.prj \
		${APPNAME}_mcc_component_data.c \
		run_${APPNAME}.sh \
		mccExcludedFiles.log \
		${APPNAME}.readme \
		readme.txt \
		${APPNAME}_mcr

distclean: clean
	rm -rf ../bin/*
