#!/bin/bash

if (( $# < 1 ))
then
  echo Not enough arguments.
  exit 1
fi

num=$1

rm -rf /tmp/client*

for (( x=0; x<$num; x++ ))
do
  (( T = $RANDOM % 20 ))
  (( S = $RANDOM % 10 ))
  echo sleeping $T.$S
  (sleep $T.$S; ./simclient render01 4000 events/event.txt > /tmp/client${x} ) &
done

