#!/bin/sh
# ----------------------------------------------------------------------
#  RAPPTURE
#
#  This is the main script that most people use to invoke the
#  Rappture GUI.  It sets environment variables so that the Rappture
#  GUI driver will work properly for the current installation.
#
# ======================================================================
#  AUTHOR:  Michael McLennan, Purdue University
#  Copyright (c) 2004-2005  Purdue Research Foundation
#
#  See the file "license.terms" for information on usage and
#  redistribution of this file, and for a DISCLAIMER OF ALL WARRANTIES.
# ======================================================================
#
# If you install Rappture elsewhere, edit the line below:
RAPPTURE_INSTALL_DIR=/opt/rappture

# no need to edit the rest...
export PATH=$RAPPTURE_INSTALL_DIR/bin:$PATH
export MATLABPATH=$RAPPTURE_INSTALL_DIR/lib/matlab:$MATLABPATH
export OCTAVE_PATH=:$RAPPTURE_INSTALL_DIR/lib/octave:$OCTAVE_PATH
export LD_LIBRARY_PATH=$RAPPTURE_INSTALL_DIR/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$RAPPTURE_INSTALL_DIR/lib:$DYLD_LIBRARY_PATH
export TCL_LIBRARY=$RAPPTURE_INSTALL_DIR/lib/tcl8.4
export TK_LIBRARY=$RAPPTURE_INSTALL_DIR/lib/tk8.4
exec $RAPPTURE_INSTALL_DIR/bin/driver $*
