#!/bin/sh
# ----------------------------------------------------------------------
#  SIMSIM KICKOFF SCRIPT
#
# ======================================================================
#  AUTHOR:  Derrick S. Kearney, Purdue University
#  Copyright (c) 2004-2007  Purdue Research Foundation
#
#  See the file "license.terms" for information on usage and
#  redistribution of this file, and for a DISCLAIMER OF ALL WARRANTIES.
# ======================================================================
#
. rappture_env
exec python simsim.py $*
