#!/bin/sh

# insulate ourselves from clerk and other NFS filesystems
OLDPWD=/tmp
export OLDPWD
HOME=/tmp
export HOME
cd $HOME

DISPLAY=:0
export DISPLAY

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/X11R6/bin:/usr/bin/X11:/opt/nanovis/bin
export PATH

LD_LIBRARY_PATH="/opt/render/lib:/lib:/usr/lib:/usr/local/lib"
export LD_LIBRARY_PATH

exec /opt/nanovis/bin/nanoscale -l 4000 -b 4001 -s 172.18.3.255 -c /opt/nanovis/bin/nanovis > /dev/null 2>&1
