#!/bin/sh

# insulate ourselves from clerk and other NFS filesystems
OLDPWD=/tmp
export OLDPWD
HOME=/tmp
export HOME
cd $HOME

DISPLAY=:0
export DISPLAY

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/X11R6/bin:/usr/bin/X11:/home/nanohub/vrinside/rappture/gui/vizservers
export PATH

#LD_LIBRARY_PATH="/opt/render/lib:/lib:/usr/lib:/usr/local/lib"
#export LD_LIBRARY_PATH

exec /home/nanohub/vrinside/rappture/gui/vizservers/nanovis/nanoscale -l 2000 -b 2001 -s 128.210.189.255 -c "/home/nanohub/vrinside/rappture/gui/vizservers/nanovis/nanovis" > /dev/null 2>&1
