# ----------------------------------------------------------------------
#  MAIN PROGRAM - generated by the Rappture Builder
# ----------------------------------------------------------------------
import Rappture
import sys

# open the XML file containing the run parameters
io = Rappture.PyXml(sys.argv[1])

#########################################################
# Get input values from Rappture
#########################################################

# get input value for input.number(x)
x = float(io['input.number(x).current'].value)

# get input value for input.number(y)
y = float(io['input.number(y).current'].value)

#########################################################
# Save output values back to Rappture
#########################################################

z = 100*(y-x**2)**2 + (1-x)**2

# save output value for output.number(z)
io['output.number(z).current'] = z

io.close()
