#! /bin/sh

rp_incls='-I../../include/octave/ -I/opt/rappture/include/core/ -I/opt/rappture/include/'
rp_lib='-L/opt/rappture/lib/ -lrappture'


mkoctfile $rp_incls $rp_lib rpAddPresets.cc
mkoctfile $rp_incls $rp_lib rpChildrenByType.cc
mkoctfile $rp_incls $rp_lib rpChildren.cc
mkoctfile $rp_incls $rp_lib rpConvert.cc
mkoctfile $rp_incls $rp_lib rpConvertDbl.cc
mkoctfile $rp_incls $rp_lib rpConvertStr.cc
mkoctfile $rp_incls $rp_lib rpConvertObjDbl.cc
mkoctfile $rp_incls $rp_lib rpConvertObjStr.cc
mkoctfile $rp_incls $rp_lib rpDefineUnit.cc
mkoctfile $rp_incls $rp_lib rpElementAsComp.cc
mkoctfile $rp_incls $rp_lib rpElementAsId.cc
mkoctfile $rp_incls $rp_lib rpElementAsObject.cc
mkoctfile $rp_incls $rp_lib rpElementAsType.cc
mkoctfile $rp_incls $rp_lib rpElement.cc
mkoctfile $rp_incls $rp_lib rpFind.cc
mkoctfile $rp_incls $rp_lib rpGetBasis.cc
mkoctfile $rp_incls $rp_lib rpGet.cc
mkoctfile $rp_incls $rp_lib rpGetString.cc
mkoctfile $rp_incls $rp_lib rpGetDouble.cc
mkoctfile $rp_incls $rp_lib rpGetExponent.cc
mkoctfile $rp_incls $rp_lib rpGetUnits.cc
mkoctfile $rp_incls $rp_lib rpGetUnitsName.cc
mkoctfile $rp_incls $rp_lib rpLib.cc
mkoctfile $rp_incls $rp_lib rpMakeMetric.cc
mkoctfile $rp_incls $rp_lib rpNodeComp.cc
mkoctfile $rp_incls $rp_lib rpNodeId.cc
mkoctfile $rp_incls $rp_lib rpNodeType.cc
mkoctfile $rp_incls $rp_lib rpPut.cc
mkoctfile $rp_incls $rp_lib rpPutDouble.cc
mkoctfile $rp_incls $rp_lib rpPutDoubleId.cc
mkoctfile $rp_incls $rp_lib rpPutString.cc
mkoctfile $rp_incls $rp_lib rpPutStringId.cc
mkoctfile $rp_incls $rp_lib rpResult.cc
mkoctfile $rp_incls $rp_lib rpXml.cc
